# Generated by Django 2.2 on 2019-06-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='Name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
