# Generated by Django 2.0.7 on 2019-06-14 09:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0002_visualization_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 6, 14, 9, 52, 27, 423633, tzinfo=utc)),
        ),
    ]
