# Generated by Django 2.0.7 on 2019-06-14 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0003_auto_20190614_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
