# Generated by Django 2.2 on 2019-06-14 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0002_auto_20190614_1127'),
        ('visualization', '0004_auto_20190614_1153'),
    ]

    operations = [
    ]
