# Generated by Django 2.2.1 on 2019-06-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0005_merge_20190614_1224'),
        ('visualization', '0005_merge_20190614_1024'),
        ('visualization', '0005_merge_20190614_1222'),
    ]

    operations = [
    ]
