# Generated by Django 2.2 on 2019-06-14 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0005_merge_20190614_1224'),
        ('visualization', '0005_merge_20190614_1024'),
    ]

    operations = [
    ]
