# Generated by Django 2.2 on 2019-06-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0007_auto_20190614_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='GraphDensity',
            field=models.IntegerField(default=0),
        ),
    ]
