# Generated by Django 2.2 on 2019-06-17 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0008_visualization_graphdensity'),
        ('visualization', '0005_merge_20190614_1222'),
    ]

    operations = [
    ]
