# Generated by Django 2.2.1 on 2019-06-17 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0006_merge_20190616_1128'),
        ('visualization', '0009_merge_20190617_1125'),
    ]

    operations = [
    ]
